version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: booktracker_db
      POSTGRES_USER: ${DB_USERNAME} # <-- Read from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <-- Read from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: booktracker_db
      DB_USERNAME: ${DB_USERNAME} # <-- Read from .env
      DB_PASSWORD: ${DB_PASSWORD} # <-- Read from .env
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY} # <-- Read from .env
      JWT_SECRET: ${JWT_SECRET} # <-- Read from .env
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data: